
version: '3.8'

services:
  proxy:
    build: ./trackhabits-proxy
    container_name: proxy
    ports:
      - "8081:8081"
    expose:
      - "8081"
    restart: unless-stopped

  site:
    build: .
    container_name: site
    ports:
      - "800:800"
    depends_on:
      - proxy
    restart: unless-stopped
